files:
  - source: /src/main/resources/Locale/JavaJavaBundle/JavaJavaTranslation.properties
    translation: /src/main/resources/Locale/JavaJavaBundle/%file_name%_%locale_with_underscore%.%file_extension%
